### ISSUE TITLE
Failed to add new team using the Admin interface

### ISSUE THREAD

**Issue by RobMackie** [alan412/CheckMeIn#23]
Looks like something changed.

How to recreate. Used values:
Team name: 
Team PyroTech - students 2019
also tried
PyroTech - students 2019
and also tried
PyroTech students 2019
pushed the "Create Team" button.
Results:

404 Not Found
Unexpected query string parameters: team_name

Traceback (most recent call last):
  File "/home/tfi/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
TypeError: admin() got an unexpected keyword argument 'team_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tfi/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/home/tfi/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/home/tfi/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/tfi/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    raise sys.exc_info()[1]
  File "/home/tfi/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 58, in __call__
    test_callable_spec(self.callable, self.args, self.kwargs)
  File "/home/tfi/CheckMeIn/venv3/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 191, in test_callable_spec
    raise cherrypy.HTTPError(404, message=message)
cherrypy._cperror.HTTPError: (404, 'Unexpected query string parameters: team_name')

**Comment by alan412** [comment]
Weird.  I just tried it and added the team and it worked fine for me.
